project:
  type: website
  output-dir: docs

website:
  title: "Trial_title_here"
  navbar:
    left:
      - href: index_new.qmd
        text: Home
  sidebar:
    style: "floating"
    search: true
    contents:
      - section: "teaching sections"
        contents:
          - markdown_new.qmd
          
  page-footer:
      left:
        "This page was built by [Quarto](https://quarto.org/).
        Copyright 2024, Gloria Shirima"
      right:
        - icon: github

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

